Mega-PR combining all the PRs
antimatter-dimensions/notations pull request #44
Opened 2019-12-07 23:59 UTC by dan-simon

This combines everything into one PR to avoid horrible merge conflicts and get community notations in the right folder (from now on I'm not going to do the work of putting community notations in the community folder, though). It also adds another community notation. I'm mostly making it a PR right now to see the code quality problems.

2019-12-09 18:26 UTC, razenpok requested changes
I didn't nitpick performance or structure of community notations since they are not a part of AD. I'm leaving them to your discretion.

I'm also awaiting a response from AD team regarding #41, so I'd suggest waiting for a bit before merging

2019-12-09 18:26 UTC, razenpok commented on src/utils.ts
> +export function toSubscript(num: number): string {
```suggestion
export function toSubscript(value: number): string {
```

2019-12-09 18:26 UTC, razenpok commented on src/utils.ts
> +export function toSuperscript(num: number): string {
```suggestion
export function toSuperscript(value: number): string {
```

2019-12-09 18:26 UTC, razenpok commented on src/notation.ts
> +  public formatNegativeVerySmallDecimal(value: Decimal, places: number): string {
```suggestion
  public formatVerySmallNegativeDecimal(value: Decimal, places: number): string {
```

2019-12-09 18:26 UTC, razenpok commented on src/notation.ts
> +  public formatVerySmallDecimal(_value: Decimal, places: number): string {
```suggestion
  public formatVerySmallDecimal(value: Decimal, places: number): string {
```

2019-12-09 18:26 UTC, Razenpok commented on src/community/precise-prime.ts
> +
Excess empty line

2019-12-09 21:47 UTC, dan-simon commented on src/notation.ts
> +  public formatVerySmallDecimal(_value: Decimal, places: number): string {
I'm not sure if changing 0 to value.toNumber() was part of this, but it seemed wise.

2019-12-09 21:53 UTC, dan-simon commented
I'd appreciate nitpicks on community notations if you want to provide them and have the time. I'd especially like to know if Precise Prime is currently too slow to be in the main game (of course I'm not going to replace Prime with it without strong tester consensus including you and Iker, but in case it does eventually replace Prime it seems important to know).

2019-12-10 19:32 UTC, Razenpok commented
Sorry, but I think in case of me actually having some spare time, I'd better put it into AD development (still in hopes to release it somewhere during 2020).

Of course if we suddenly decide to incorporate some notation into base pack, it will undergo an additional performance and code style review. Until that it's fine if the community notations are not up to the _highest_ quality we can achieve (just keep them clean and reasonable).

2019-12-10 19:32 UTC, razenpok approved these changes

2019-12-11 11:45 UTC, merged